export const CREATE_TASK = 'TODO_CREATE_TASK';

export const FETCH_ALL = 'TODO_FETCH_ALL';

export const UPDATE_TASK = 'TODO_UPDATE_TASK';

export const DELETE_TASK = 'TODO_DELETE_TASK';

export const DELETE_COMPLETED = 'TODO_DELETE_COMPLETED';
